services:
  backend:
    build: ./backend
    container_name: flowboard-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app     # live reload for backend

  frontend:
    build: ./frontend
    container_name: flowboard-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app        # hot reload for frontend
      - /app/node_modules
    depends_on:
      - backend
